console.log("Hello World!")
console.log(5+5)
console.log(5*8)
console.log("Hello World!")
console.log(5+5)
console.log(5*8)
console.log("Hello World!")
console.log(5+5)
console.log(5*8)
console.log("Hello World!")
console.log(5+5)
console.log(5*8)
console.log("Hello World!")
console.log(5+5)
console.log(5*8)
console.log("Hello World!")
console.log(5+5)
console.log(5*8)